version: '3.1'

services:

  db:
    container_name: spring-data
    image: mariadb
    environment:
      MARIADB_DATABASE: spring-data
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"